package com.smartstyle.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class OutfitAnalysisDaoTest {

    private lateinit var db: AppDatabase
    private lateinit var dao: OutfitAnalysisDao

    @Before
    fun setup() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            AppDatabase::class.java
        ).allowMainThreadQueries().build()
        dao = db.outfitAnalysisDao()
    }

    @After
    fun teardown() = db.close()

    private fun entity(
        assessment: String = "Nice outfit.",
        suggestions: String = "Tip one\nTip two",
        tags: String = "casual,summer",
        timestamp: Long = System.currentTimeMillis()
    ) = OutfitAnalysisEntity(
        imageUri = "/path/to/image.jpg",
        assessment = assessment,
        suggestions = suggestions,
        tags = tags,
        mlKitLabels = "Jeans,Shirt",
        timestamp = timestamp
    )

    @Test
    fun insert_andQuery_returnsInsertedEntity() = runBlocking {
        dao.insert(entity(assessment = "Cool look."))

        val results = dao.getAllAnalyses().first()

        assertEquals(1, results.size)
        assertEquals("Cool look.", results[0].assessment)
    }

    @Test
    fun insert_assignsAutoGeneratedId() = runBlocking {
        val id = dao.insert(entity())
        assertTrue(id > 0)
    }

    @Test
    fun insert_multipleEntities_allReturned() = runBlocking {
        dao.insert(entity(assessment = "First"))
        dao.insert(entity(assessment = "Second"))
        dao.insert(entity(assessment = "Third"))

        val results = dao.getAllAnalyses().first()
        assertEquals(3, results.size)
    }

    @Test
    fun getAllAnalyses_orderedByTimestampDescending() = runBlocking {
        dao.insert(entity(assessment = "Oldest", timestamp = 1000L))
        dao.insert(entity(assessment = "Newest", timestamp = 3000L))
        dao.insert(entity(assessment = "Middle", timestamp = 2000L))

        val results = dao.getAllAnalyses().first()

        assertEquals("Newest", results[0].assessment)
        assertEquals("Middle", results[1].assessment)
        assertEquals("Oldest", results[2].assessment)
    }

    @Test
    fun deleteById_removesCorrectEntity() = runBlocking {
        val id1 = dao.insert(entity(assessment = "Keep me"))
        val id2 = dao.insert(entity(assessment = "Delete me"))

        dao.deleteById(id2)

        val results = dao.getAllAnalyses().first()
        assertEquals(1, results.size)
        assertEquals("Keep me", results[0].assessment)
    }

    @Test
    fun deleteById_nonExistentId_doesNotAffectOtherRows() = runBlocking {
        dao.insert(entity(assessment = "Should remain"))

        dao.deleteById(999L)

        val results = dao.getAllAnalyses().first()
        assertEquals(1, results.size)
    }

    @Test
    fun emptyDatabase_returnsEmptyList() = runBlocking {
        val results = dao.getAllAnalyses().first()
        assertTrue(results.isEmpty())
    }

    @Test
    fun insert_persistsAllFields() = runBlocking {
        dao.insert(entity(
            assessment = "Bold and colourful.",
            suggestions = "Try monochrome\nAdd a scarf",
            tags = "bold,colourful,autumn",
            timestamp = 12345L
        ))

        val result = dao.getAllAnalyses().first()[0]

        assertEquals("Bold and colourful.", result.assessment)
        assertEquals("Try monochrome\nAdd a scarf", result.suggestions)
        assertEquals("bold,colourful,autumn", result.tags)
        assertEquals(12345L, result.timestamp)
    }
}
